- name: Setup config dir
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: "0700"

- name: Install Config
  ansible.builtin.copy:
    src: ".ssh"
    dest: "{{ ansible_env.HOME }}/"
    owner: "{{ ansible_env.USER }}"
    mode: "0700"
