- name: Check Install
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.dotconfigs"
  register: dotconfigs_path_result

- name: Install Dotconfigs
  ansible.builtin.git:
    repo: 'git@github.com:winetree94/dotconfigs.git'
    dest: "{{ ansible_env.HOME }}/.dotconfigs"
    version: main
  become: true
  become_user: "{{ ansible_env.USER }}"
  when: not dotconfigs_path_result.stat.exists
