- name: Setup SSH Environment
  hosts: windows-machines
  become: true
  roles:
    - ssh
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: |
          user: {{ ansible_env.USER }} \n
          home: {{ ansible_env.HOME }}
