- name: Setup Development Environment
  # hosts: local-machines
  # hosts: dev-debian
  hosts: all
  # become: true
  vars:
    gui: false
    is_linux: "{{ ansible_os_family != 'Darwin' }}"
    is_macos: "{{ ansible_os_family == 'Darwin' }}"
  roles:
    - role: apt-update
      when: is_linux
    - role: setup-snap
      when: is_linux
    - role: setup-flatpak
      when: is_linux
    - setup-homebrew
    - role: rust
    - role: python3
    - role: git
      when: is_linux
    - role: better-cli-tools
    - role: zsh
    - role: tmux
    - role: bw
    - role: nvim
    - role: kubectl
    - role: docker
      when: is_linux
    - role: stow
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: |
          user: {{ ansible_env.USER }} \n
          home: {{ ansible_env.HOME }} \n
          platform: {{ ansible_os_family }}
